SELECT
    CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) as AVERAGE_DURATION
from
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
group BY 
    CAR_ID
HAVING
  AVERAGE_DURATION >= 7
ORDER BY
    AVERAGE_DURATION DESC, CAR_ID DESC
;